apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: EXAMPLE-NAMESPACE
spec:
  selector:
    app: nexus-app
  ports:
    - protocol: TCP
      port: 8081 # Nexus默认端口号，与部署中的容器端口保持一致
      targetPort: 8081 # Nexus容器内部监听的端口号，与容器内的应用配置一致
  type: LoadBalancer # 根据需求调整为LoadBalancer或ClusterIP

