kind: Deployment
apiVersion: apps/v1
metadata:
  name: bcia-redis
  namespace: EXAMPLE-NAMESPACE

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bcia
      ms-name: redis
  template:
    metadata:
      name: bcia-redis
      namespace: EXAMPLE-NAMESPACE
      labels:
        app: bcia
        ms-name: redis
    spec:
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: EXAMPLE-PVC-NAME
        - name: redis-config
          configMap:
            name: redis-conf
            items:
              - key: redis.conf
                path: redis.conf
            defaultMode: 420
      containers:
        - name: bcia-redis
          image: redis:5.0.5
          command:
            - redis-server
          args:
            - /usr/local/etc/redis.conf
          resources: {}
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /usr/local/etc
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

