kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: EXAMPLE-PVC-NAME
  namespace: EXAMPLE-NAMESPACE
  labels:
    ## This is the namespace of the PVC
    dir: EXAMPLE-NAMESPACE
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-subdir-client
  volumeMode: Filesystem
